manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: elvishuynh
      url-base: https://github.com/elvishuynh

  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: ncs
      revision: v3.3.1
      import: true

    - name: zephyr-tm1640-driver
      remote: elvishuynh
      revision: main

    - name: pt18-led-matrix-module
      remote: elvishuynh
      revision: main

  self:
    path: nrf-pt18-tm1640-demo